### ISSUE TITLE
Problem with MySQL: Error creating bean with name 'searchableClassMappingConfigurator'

### ISSUE THREAD

**Issue by joergrech** [mstein/elasticsearch-grails-plugin#21]
Hi,
  I have a problem starting an app in production mode with mysql. It works with the H2 database in development mode but in production mode I get the following error:

| Error 2012-04-15 10:52:56,837 [pool-7-thread-1] ERROR [localhost].[/AppConfigurator]  - Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
Message: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is org.elasticsearch.discovery.MasterNotDiscoveredException: 
   Line | Method
->> 303 | innerRun in java.util.concurrent.FutureTask$Sync

---

|   138 | run      in java.util.concurrent.FutureTask
|   886 | runTask  in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run      in     ''
^   619 | run . .  in java.lang.Thread
Caused by MasterNotDiscoveredException: 
->> 162 | onTimeout in org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$3

---

|   332 | run      in org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout
|   886 | runTask  in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run      in     ''
^   619 | run . .  in java.lang.Thread
| Error 2012-04-15 10:52:56,891 [pool-7-thread-1] ERROR core.StandardContext  - Error listenerStart
| Error 2012-04-15 10:52:56,896 [pool-7-thread-1] ERROR core.StandardContext  - Context [/AppConfigurator] startup failed due to previous errors

**Comment by mstein** [comment]
The error seems doesn't seems to be linked to the database. Your elasticSearch.client.mode config key may be different in production environment.

By default, it is set to "local" in dev & test mode, which means that it launch an embedded ES instance on startup.
In production mode, that setting is set to "node" by default, assuming you have a separated ES instance running somewhere on the local network or on the same host.

Whether change this setting or start a separate ES instance.

**Comment by joergrech** [comment]
Great! That helped me a lot!

**Comment by pavithraNovember** [comment]
Im not able to understand this can you please explain... I m running into the same issue...
