### ISSUE TITLE
Using the plugin as a replacement of default GORM

### ISSUE THREAD

**Issue by ginaluca** [mstein/elasticsearch-grails-plugin#48]
Hi,

I understand that this plugin works aside the Hibernate GORM, by indexing what is persisted to DB. 

I'm interested in scenarios where elastic search is the only datastore used by the application, without any DB involved. What would it be the effort of adapting elasticsearch-grails-plugin in that sense? Rewriting some classes, or adding big parts of new code, or..? 

  Gianluca

**Comment by mstein** [comment]
To use it as a "complete replacement" to GORM, there would be a lot of new code to add (as the plugin is not an implementation to grails-datastore).
The first thing to do would be to dissociate the plugin from Hibernate I guess.

**Comment by ginaluca** [comment]
OK, and after removing Hibernate I might use one of the plugins in grails-data-mapping as a model for how to continue. Interesting idea for a fork.

Thanks,
  Gianluca
