### ISSUE TITLE
SearchableClassMappingConfigurator waits for green status

### ISSUE THREAD

**Issue by tcrossland** [mstein/elasticsearch-grails-plugin#6]
Hi Manuarii,

When running elasticsearch with a single node, the cluster health will never become "Green" as none of the shards are replicated. 
I guess this is a fairly common scenario (especially in dev/test environments).

The problem with waitForGreenStatus() is that it adds 30 seconds to application startup time. I've made a change to use waitForYellowStatus() instead, not sure if this could have implications in multi-node clusters.

Thanks!

**Comment by mstein** [comment]
Hi, you're right, I don't think it would be a issue, I've also changed it in the latest head for now.
