### ISSUE TITLE
DeleteIndex and Refresh don't work

### ISSUE THREAD

**Issue by ramzimaalej** [mstein/elasticsearch-grails-plugin#73]
No signature of method: org.elasticsearch.action.admin.indices.refresh.RefreshResponse.failedShards() is applicable for argument types: () values: []
Possible solutions: getFailedShards(). Stacktrace follows:
Message: No signature of method: org.elasticsearch.action.admin.indices.refresh.RefreshResponse.failedShards() is applicable for argument types: () values: []
Possible solutions: getFailedShards()
   Line | Method
->>  37 | doCall            in org.grails.plugins.elasticsearch.ElasticSearchAdminService$_refresh_closure1

---

|    14 | withElasticSearch in org.grails.plugins.elasticsearch.ElasticSearchHelper
|    29 | refresh . . . . . in org.grails.plugins.elasticsearch.ElasticSearchAdminService
|    51 | refresh           in     ''
|    15 | reindexcontent .  in net.safetynotes.admin.web.ServerController$$EOMkikls
|   195 | doFilter          in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|    63 | doFilter . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|   895 | runTask           in java.util.concurrent.ThreadPoolExecutor$Worker
|   918 | run . . . . . . . in     ''
^   695 | run               in java.lang.Thread

**Comment by mstein** [comment]
Duplicate for #67
