### ISSUE TITLE
geo_point and geo_distance

### ISSUE THREAD

**Issue by gmaiztegi** [mstein/elasticsearch-grails-plugin#8]
Hi there,
I'm trying to use the geo_point type and the geo_distance filter for geospatial queries but I don't see anything regarding this in the docs. Is there any guide that could help me with this?
Thank you in advance.

**Comment by mstein** [comment]
Hi, the plugin doesn't provide any conveniences methods for geo location currently. You may want to use the low lvl API to do what you want until we add this in the plugin (I've added a task for that on the project tracker).
See the ElasticSearch documentation on their website for more info on the API.

**Comment by gmaiztegi** [comment]
Ok, I'll try to work with the API.
Thanks for your work.
